name = "VintageRemix"
author = "unilock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da946cb5da51b7336a34bfd200b6dcfbcfb1cae70890d14b01db80db2c3f1508"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
unsup = "1.2.0-pre4"

[options]
acceptable-game-versions = ["1.12", "1.12.1", "1.12.2"]
