name = "VintageRemix"
author = "unilock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a78f3d2daebec77b2ad98faf88fe66c2187e042c4913bab88a1c0b4645def13"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
unsup = "1.2.0-pre4"

[options]
acceptable-game-versions = ["1.12", "1.12.1", "1.12.2"]
