name = "VintageRemix"
author = "unilock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "012f32c074aa67ad97982f81fd1e6c29e6658a8cebc2b20a333f9b74ef212175"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["1.12", "1.12.1", "1.12.2"]
